CREATE TABLE payments (
  id INT NOT NULL AUTO_INCREMENT,
  status TINYINT NOT NULL DEFAULT 0,
  salt VARCHAR(64) NOT NULL,
  address VARCHAR(42) NOT NULL,
  amount INT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
